### ISSUE TITLE
No changes after changing the texture of the original HUD (inside car)

### ISSUE THREAD

**Issue by itsERRvlad** [Max98/project_nodeSnap#15]
I've tweaked the original HUD texture, but the game doesn't see the change. What should I do to change the texture? I tried to save in a .dds file and in .in the truck file, specify this file in the HUD, but the improvements are not visible.

**Comment by Max98** [comment]
I don't understand, nodeSnap doesn't have such a feature (to edit HUD textures). Maybe you should post in the [forums](https://forum.rigsofrods.org/forums/content-support.10/).
