### ISSUE TITLE
how do I open this?

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Max98/project_nodeSnap#2]
there's no exe

**Comment by umustbeloggedintododat** [comment]
Why the tag?

**Comment by Max98** [comment]
> Why the tag?

Because this is a source code, not an application. You have to 'build' the 'exe' by yourself.
This is irrelevant to the project as an issue.

I'll release a little tutorial on how to compile the project.

**Comment by umustbeloggedintododat** [comment]
oh ok
