### ISSUE TITLE
help I did npm install but there's no exe

### ISSUE THREAD

**Issue by umustbeloggedintododat** [Max98/project_nodeSnap#3]
I'm on windows btw 
I opened command prompt and set it to the nodesnap directory, and wrote "npm install".
after it finished all it did was create a folder that had even more useless stuff I can't open. There's no executable. Am I doing this wrong? I really want to start RoR modding!

**Comment by umustbeloggedintododat** [comment]
BUMP

**Comment by umustbeloggedintododat** [comment]
I finally did it by inputting "electron:serve"

**Comment by Max98** [comment]
Fixed in https://github.com/Max98/project_nodeSnap/commit/b66cd018cee2215803db32fb06db06c0ee33e2e4
